name: Deploy FastAPI with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Pull Docker Image from Docker Hub
      run: docker pull mithunjackson/ml-fastapi:latest

    - name: Run Docker Container
      run: docker run -d -p 8000:8000 mithunjackson/ml-fastapi:latest
